### ISSUE TITLE
Create Agent Fails when optional `Memory soft limit` or `Maximum hard limit` is not specified on EA profile

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd-contrib/docker-swarm-elastic-agents#53]
Create Agent request fails with following exception when `MaxMemory` or `ReservedMemory` is not specified:
```
2018-01-16 12:13:26,191 ERROR [1144@MessageListener for CreateAgentListener] DockerPlugin:82 - Failed to handle request go.cd.elastic-agent.create-agent due to:
java.lang.IllegalArgumentException: Invalid size:
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at cd.go.contrib.elasticagents.dockerswarm.elasticagent.utils.Size.parse(Size.java:83)
	at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerService.requirements(DockerService.java:138)
	at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerService.create(DockerService.java:111)
	at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerServices.create(DockerServices.java:49)
	at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerServices.create(DockerServices.java:34)
	at cd.go.contrib.elasticagents.dockerswarm.elasticagent.executors.CreateAgentRequestExecutor.execute(CreateAgentRequestExecutor.java:44)
	at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.handle(DockerPlugin.java:55)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:162)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:316)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:162)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.createAgent(ElasticAgentExtension.java:71)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.createAgent(ElasticAgentPluginRegistry.java:41)
	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:32)
	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:22)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:745)
```

##### Possible Fix
Do not parse resource limits and resource reservations when not specified in the EA profile.

**Comment by bdpiparva** [comment]
This is fixed in PR https://github.com/gocd-contrib/docker-swarm-elastic-agents/pull/58
